### ISSUE TITLE
no available docker image

### ISSUE THREAD

**Issue by fangdaoyou** [VinAIResearch/Counting-DETR#11]
there is no quaden/docker_images:pytorch_cuda102 image in docker hub

**Comment by cmgyqjj** [comment]
Have you solved this problem? About no available docker image

**Comment by cmgyqjj** [comment]
@fangdaoyou  Have you solved this problem? About no available docker image @

**Comment by NguyenVanThanhHust** [comment]
sorry for late reply, I'm too busy with other project. Basically, you can use any pytorch docker, and install other package with pip
