### ISSUE TITLE
Could you please share the dataset download link?

### ISSUE THREAD

**Issue by Tracyummy** [VinAIResearch/Counting-DETR#3]

**Comment by NguyenVanThanhHust** [comment]
sorry, Due to some errror in google drive, I would update other download link asap

**Comment by NguyenVanThanhHust** [comment]
@Tracyummy Can you use other link in readme?

**Comment by Tracyummy** [comment]
> @Tracyummy Can you use other link in readme?

yeah, I see. thanks!

**Comment by cripsgreen** [comment]
Hello, I have the same question as you. Have you resolved it now? @Tracyummy
